clusters: clusters.c
	gcc clusters.c -o clusters -lallegro -lallegro_primitives -lallegro_image -lm -lallegro_font -lallegro_ttf -Wall -Werror -Wextra

game_of_life: game_of_life.c
	gcc game_of_life.c -lallegro -lallegro_font -lallegro_image -lallegro_primitives -Wall -Werror -Wextra
